//! Versioned HTTP and WebSocket payloads shared by the Rust services.

use serde::{Deserialize, Serialize};
use serde_json::Value;
use ts_rs::{Config, TS};

/// Current wire protocol version.
pub const PROTOCOL_VERSION: u16 = 1;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
pub struct HealthResponse {
    pub status: String,
    pub service: String,
    pub protocol_version: u16,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, TS)]
pub struct ReadinessResponse {
    pub status: String,
    pub database: bool,
    pub redis: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, TS)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ClientMessage {
    Ping {
        request_id: String,
    },
    Broadcast {
        topic: String,
        #[ts(type = "JsonValue")]
        payload: Value,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, TS)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum ServerMessage {
    Connected {
        protocol_version: u16,
    },
    Pong {
        request_id: String,
    },
    Broadcast {
        topic: String,
        #[ts(type = "JsonValue")]
        payload: Value,
    },
    Error {
        code: String,
    },
}

/// Generate the committed TypeScript wire contract from the Rust source of truth.
#[must_use]
pub fn typescript_bindings() -> String {
    let config = Config::new();
    let declarations = [
        HealthResponse::decl(&config),
        ReadinessResponse::decl(&config),
        ClientMessage::decl(&config),
        ServerMessage::decl(&config),
    ];
    let mut output = format!(
        "// @generated by `cargo run -p slide-helper-protocol --bin export-types`.\n// Do not edit this file by hand.\n\nexport const PROTOCOL_VERSION = {PROTOCOL_VERSION} as const;\n\nexport type JsonPrimitive = null | boolean | number | string;\nexport type JsonValue =\n  | JsonPrimitive\n  | JsonValue[]\n  | {{ [key: string]: JsonValue }};\n\n"
    );

    for declaration in declarations {
        output.push_str("export ");
        output.push_str(&declaration);
        output.push_str("\n\n");
    }

    output
}

#[cfg(test)]
mod tests {
    use super::{ClientMessage, PROTOCOL_VERSION, ServerMessage, typescript_bindings};
    use serde_json::json;

    #[test]
    fn websocket_messages_use_versioned_tagged_json() {
        let encoded = serde_json::to_value(ServerMessage::Connected {
            protocol_version: PROTOCOL_VERSION,
        })
        .expect("message should serialize");

        assert_eq!(encoded, json!({"type": "connected", "protocol_version": 1}));
    }

    #[test]
    fn client_broadcast_round_trips() {
        let message = ClientMessage::Broadcast {
            topic: "m0".to_owned(),
            payload: json!({"slide": 5}),
        };
        let encoded = serde_json::to_string(&message).expect("message should serialize");
        let decoded: ClientMessage =
            serde_json::from_str(&encoded).expect("message should deserialize");

        assert_eq!(decoded, message);
    }

    #[test]
    fn typescript_contract_contains_version_and_tagged_unions() {
        let bindings = typescript_bindings();

        assert!(bindings.contains("export const PROTOCOL_VERSION = 1 as const"));
        assert!(bindings.contains("export type ClientMessage"));
        assert!(bindings.contains("\"type\": \"ping\""));
        assert!(bindings.contains("\"type\": \"broadcast\""));
        assert!(bindings.contains("payload: JsonValue"));
        assert!(bindings.contains("export type ServerMessage"));
    }
}
