// @generated by `cargo run -p slide-helper-protocol --bin export-types`.
// Do not edit this file by hand.

export const PROTOCOL_VERSION = 2 as const;

export type JsonPrimitive = null | boolean | number | string;
export type JsonValue =
  | JsonPrimitive
  | JsonValue[]
  | { [key: string]: JsonValue };

export type HealthResponse = { status: string, service: string, protocol_version: number, };

export type ReadinessResponse = { status: string, database: boolean, redis: boolean, };

export type ClientMessage = { "type": "ping", request_id: string, } | { "type": "subscribe", topic: string, after_sequence?: number, } | { "type": "broadcast", topic: string, payload: JsonValue, };

export type RealtimeEvent = { "event_type": "session.state_changed", status: string, sync_mode: string, current_cue_run_id: string | null, } | { "event_type": "cue.state_changed", cue_run_id: string, state: string, } | { "event_type": "presentation.position_changed", provider: string, deck_external_id: string, slide_external_id: string | null, slide_index: number, sync_mode: string, } | { "event_type": "interaction.state_changed", cue_run_id: string, interaction_id: string, state: string, } | { "event_type": "response.aggregate_updated", cue_run_id: string, interaction_id: string, aggregate: JsonValue, } | { "event_type": "audience.count_updated", count: number, } | { "event_type": "question.updated", question_id: string, status: string, vote_count: number, };

export type RealtimeEventEnvelope = { schema_version: number, event_id: string, session_id: string, sequence: number, state_version: number, occurred_at: string, event_type: string, event: RealtimeEvent, };

export type ServerMessage = { "type": "connected", protocol_version: number, } | { "type": "pong", request_id: string, } | { "type": "subscribed", topic: string, } | { "type": "event", topic: string, event: RealtimeEventEnvelope, } | { "type": "broadcast", topic: string, payload: JsonValue, } | { "type": "error", code: string, };

