// @generated by `cargo run -p slide-helper-protocol --bin export-types`.
// Do not edit this file by hand.

export const PROTOCOL_VERSION = 1 as const;

export type JsonPrimitive = null | boolean | number | string;
export type JsonValue =
  | JsonPrimitive
  | JsonValue[]
  | { [key: string]: JsonValue };

export type HealthResponse = { status: string, service: string, protocol_version: number, };

export type ReadinessResponse = { status: string, database: boolean, redis: boolean, };

export type ClientMessage = { "type": "ping", request_id: string, } | { "type": "broadcast", topic: string, payload: JsonValue, };

export type ServerMessage = { "type": "connected", protocol_version: number, } | { "type": "pong", request_id: string, } | { "type": "broadcast", topic: string, payload: JsonValue, } | { "type": "error", code: string, };

